---
title: "Projet Adenome"
author: "Zineb Bennis & Fabrice Sougey"
date: "December 4, 2017"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup,echo=FALSE}
setwd("/home/sougeyf/TP_Adenome")
library(ggplot2)
library(corrplot)
theme_set(theme_classic())
```

#
# Plot functions
#
```{r functions,echo=FALSE}
adenome_boxplot <- function(df, feature_index){
  title = "Boxplot"
  x_axis = colnames(df)[feature_index]
  caption = "Source : ADENOME-PROS"

  g <- ggplot(df, aes("", df[,feature_index]))
  g <- g + geom_boxplot(varwidth=T, fill="plum")
  g <- g + labs(title=title, 
         subtitle=x_axis,
         caption=caption,
         x=x_axis)
  print(g)
}

adenome_scatterplot <- function(df, feature_index_i, feature_index_j) {
  title = "Scatterplot"
  x_axis = colnames(df)[feature_index_i]
  y_axis = colnames(df)[feature_index_j]
  subtitle = paste(x_axis, " Vs. ", y_axis)
  caption = "Source : ADENOME-PROS"
  g <- ggplot(df, aes(x=df[,feature_index_i], y=df[,feature_index_j]))
  g <- g + geom_point()
  g <- g + labs(title=title,subtitle=subtitle,y=y_axis,x=x_axis,caption=caption)
  print(g)
}

adenome_barplot <- function(df, feature_index) {
  title = "Barplot"
  caption = "Source : ADENOME-PROS"
  x_axis = colnames(df)[feature_index]
  g <- ggplot(df, aes(df[,feature_index]))
  g <- g + geom_bar(width = 0.5)
  g <- g + labs(title=title, 
         subtitle=x_axis,
         caption=caption,
         x=x_axis,
         y="")
  print(g)
}
```

#
# Cleanup & Data Preparation
#
```{r cleanup,echo=FALSE}

# Les fichiers ont été transformés et nettoyés en CSV avant import dans R

vapor<-read.csv(file = "datasets/VAPOR.csv", sep = ",")
rtupb<-read.csv(file = "datasets/RTUPB-VBPPS.csv", sep = ",")

# On cree  une variable vapor_pre_cor pour creer une matrice de correlation ne comportant que des donnees numeriques
vapor_pre_cor=vapor[1:20]
vapor_pre_cor=subset(vapor_pre_cor,select=-c(Comorbidite,Porteur_Sonde,Indication,Anesthesie,Evenement,Transfusion,QoL,Caillotage,Reprise_Bloc,Technique))
rtupb_pre_cor=rtupb[1:20]
rtupb_pre_cor=subset(rtupb_pre_cor,select=-c(Comorbidite,Porteur_Sonde,Indication,Anesthesie,Evenement,Transfusion,QoL,Caillotage,Reprise_Bloc,Technique))

################################# VAPOR ###############################################
# Cast des variables booléennes
vapor$Comorbidite<-as.logical(vapor$Comorbidite)
vapor$Porteur_Sonde<-as.logical(vapor$Porteur_Sonde)
vapor$Transfusion<-as.logical(vapor$Transfusion)
vapor$Caillotage<-as.logical(vapor$Caillotage)
vapor$Reprise_Bloc<-as.logical(vapor$Reprise_Bloc)

# Cast des variables catégoriques
vapor$Indication<-as.factor(vapor$Indication)
vapor$Anesthesie<-as.factor(vapor$Anesthesie)
vapor$Evenement<-as.factor(vapor$Evenement)
vapor$Technique<-as.factor(vapor$Technique)

# Cast des variables catégoriques ordonnées
vapor$QoL<-as.ordered(vapor$QoL)
vapor$X1M_QoL<-as.ordered(vapor$X1M_QoL)
vapor$X3M_QoL<-as.ordered(vapor$X3M_QoL)
vapor$X6M_QoL<-as.ordered(vapor$X6M_QoL)
vapor$X9M_QoL<-as.ordered(vapor$X9M_QoL)
vapor$X12M_QoL<-as.ordered(vapor$X12M_QoL)
vapor$X15M_QoL<-as.ordered(vapor$X15M_QoL)
vapor$X18M_QoL<-as.ordered(vapor$X18M_QoL)

# 20 premières colonnes du dataset -> pré-opératoire
vapor_pre<-vapor[,1:20]

# Dernières colonnes du dataset -> post-opératoire
vapor_post<-vapor[,21:41]

####################################### RTUPB #########################################

# Cast des variables booléennes
rtupb$Comorbidite<-as.logical(rtupb$Comorbidite)
rtupb$Caillotage<-as.logical(rtupb$Caillotage)
rtupb$Porteur_Sonde<-as.logical(rtupb$Porteur_Sonde)
rtupb$Reprise_Bloc<-as.logical(rtupb$Reprise_Bloc)
rtupb$Transfusion<-as.logical(rtupb$Transfusion)

# Cast des variables catégoriques
rtupb$Indication<-as.factor(rtupb$Indication)
rtupb$Anesthesie<-as.factor(rtupb$Anesthesie)
rtupb$Evenement<-as.factor(rtupb$Evenement)
rtupb$Technique<-as.factor(rtupb$Technique)

# Cast des variables catégoriques ordonnées 
rtupb$QoL<-as.ordered(rtupb$QoL)
rtupb$X1M_QoL<-as.ordered(rtupb$X1M_QoL)
rtupb$X3M_QoL<-as.ordered(rtupb$X3M_QoL)
rtupb$X6M_QoL<-as.ordered(rtupb$X6M_QoL)
rtupb$X9M_QoL<-as.ordered(rtupb$X9M_QoL)
rtupb$X18M_QoL<-as.ordered(rtupb$X18M_QoL)

# 20 premières colonnes du dataset -> pré-opératoire
rtupb_pre<-rtupb[,1:20]

# Dernières colonnes du dataset -> post-opératoire
rtupb_post<-rtupb[,21:41]
```

## Analyse des donnees Pre-operatoire VAPOR.
```{r vapor_pre,echo=FALSE}

#
# Analyse Exploratoire de Vapor
#
# Boxplots des variables numériques et barplots des variables catégoriques
par(mfrow = c(2,1))
for (i in 1:ncol(vapor_pre)) {
  #x11(display="")
  if (is.numeric(vapor_pre[,i]) || is.integer(vapor_pre[,i])) {
    adenome_boxplot(vapor_pre,i)
  }
  else
    adenome_barplot(vapor_pre,i)
}
```

## Analyse des donnees Post-operatoire VAPOR.
```{r vapor_post,echo=FALSE}

par(mfrow = c(1,1))
for (i in 1:ncol(vapor_post)) {
  #x11(display="")
  if (is.numeric(vapor_post[,i]) || is.integer(vapor_post[,i]))
    adenome_boxplot(vapor_post,i)
  else
    adenome_barplot(vapor_post,i)
}
```

## Analyse des donnees Pre-operatoire RTUPB.
```{r rtupb_pre,echo=FALSE}

# Analyse Exploratoire de RTUPB
#
# Boxplots des variables numériques et barplots des variables catégoriques
par(mfrow = c(1,1))
for (i in 1:ncol(rtupb_pre)) {
  #x11(display="")
  if (is.numeric(rtupb_pre[,i]) || is.integer(rtupb_pre[,i]))
    adenome_boxplot(rtupb_pre,i)
  else
    adenome_barplot(rtupb_pre,i)
}
```

## Analyse des donnees Post-operatoire RTUPB.
```{r rtupb_post,echo=FALSE}

par(mfrow = c(1,1))
for (i in 1:ncol(rtupb_post)) {
  #x11(display="")
  if (is.numeric(rtupb_post[,i]) || is.integer(rtupb_post[,i]))
    adenome_boxplot(rtupb_post,i)
  else
    adenome_barplot(rtupb_post,i)
}

# On cree une matrice de correlation pour voir les liens entre les variables 
Matrice_cor_vapor=cor(vapor_pre_cor, method = c("pearson"))
corrplot(Matrice_cor_vapor, type="upper",tl.col="black", tl.srt=45)
Matrice_cor_rtupb=cor(rtupb_pre_cor, method = c("pearson"))
corrplot(Matrice_cor_rtupb, type="upper",tl.col="black", tl.srt=45)
```

```{r PAM,echo=FALSE}
# On enleve les variables qui ne rapportent rien cad qui ot la meme valeur pour tout les individus et on redivise en post et pre operatoires

vapor_small=subset(vapor,select=-c(Technique))
vapor_small_pre=vapor_small[1:19]
vapor_small_post=vapor_small[20:40]
rtupb_small=subset(rtupb,select=-c(Evenement,Reprise_Bloc,Transfusion))
rtupb_small_pre=rtupb_small[1:17]
rtupb_small_post=rtupb_small[17:38]

# On fait CAH ensuite PAM afin de determiner les profils types: 
resu_cah_vapor=hclust(daisy(vapor_small_pre),method = "ward.D")
plot(resu_cah_vapor)
resu_pam_vapor=pam(daisy(vapor_small_pre),14)
plot(resu_pam_vapor)

resu_cah_rtupb=hclust(daisy(rtupb_small_pre),method = "ward.D")
plot(resu_cah_rtupb)
resu_pam_rtupb=pam(daisy(rtupb_small_pre),26)
plot(resu_pam_rtupb)
````
